"""Conformer- and cluster-level entropy analysis for ensembles."""

from __future__ import annotations

import math
from collections.abc import Sequence
from typing import Any

from ensemblelab.analysis.clusters import Basin, cluster_basins
from ensemblelab.analysis.entropy import entropy_statistics
from ensemblelab.analysis.populations import DEFAULT_TEMPERATURE_K, analyze_populations
from ensemblelab.generators import Conformer, Ensemble

CLUSTERING_METHOD = "greedy_best_fit_rmsd"
CLUSTERING_DISTANCE = "RDKit best-fit RMSD"


def analyze_entropy(
	ensemble: Ensemble,
	temperature: float = DEFAULT_TEMPERATURE_K,
	*,
	conformers: Sequence[Conformer] | None = None,
	basins: Sequence[Basin] | None = None,
	rmsd_threshold: float = 0.75,
) -> dict[str, Any]:
	"""Calculate conformer- and cluster-level entropy for an ensemble.

	Boltzmann populations are calculated by :func:`analyze_populations`.
Clusters are either generated by the existing :func:`cluster_basins` API or
provided as existing ``Basin`` objects. Supplied assignments are used as-is
and must define a complete, non-overlapping partition for cluster entropy to
be available.

	Parameters
	----------
	ensemble
		Source ensemble.
	temperature
		Positive finite temperature in kelvin, passed through to the population
		analysis and recorded in the summary.
	conformers
		Optional ordered subset of conformers owned by the ensemble.
	basins
		Optional existing basin assignments. If omitted, use
		:func:`cluster_basins` with ``rmsd_threshold``. If supplied, assignments
		are validated for coverage but are not regenerated or altered.
	rmsd_threshold
		Positive finite best-fit RMSD cutoff in angstroms, used only when basins
		are generated by this function.

	Returns
	-------
	dict
		Mappings named ``conformers``, ``clusters``, and ``summary``. Invalid
		populations remain ``None`` and are excluded, never treated as zero.
		Cluster entropy requires complete cluster assignment and is calculated
		from the summed member conformer populations.

	Notes
	-----
	Entropy is in nats (natural logarithms); effective size is its exponential.
	Conformer-level entropy may be inflated by redundant conformers. Cluster
	results depend on the clustering method and cutoff and are not an absolute
	measure of thermodynamic conformational entropy.
	"""
	if basins is None and (
		isinstance(rmsd_threshold, bool)
		or not isinstance(rmsd_threshold, (int, float))
		or not math.isfinite(float(rmsd_threshold))
		or rmsd_threshold <= 0
	):
		raise ValueError("rmsd_threshold must be a positive finite value in angstroms.")
	selected = list(ensemble.conformers if conformers is None else conformers)
	population_result = analyze_populations(
		ensemble, temperature, conformers=selected
	)
	conformer_rows = population_result["conformers"]

	if basins is None:
		selected_basins = (
			cluster_basins(
				ensemble,
				conformers=selected,
				rmsd_threshold=float(rmsd_threshold),
				temperature=temperature,
			)
			if selected
			else []
		)
		clustering_method = CLUSTERING_METHOD
		clustering_distance = CLUSTERING_DISTANCE
		clustering_threshold: float | None = float(rmsd_threshold)
	else:
		selected_basins = list(basins)
		clustering_method = "provided_basin_assignments"
		clustering_distance = None
		clustering_threshold = None

	assignment_complete = not (selected and not selected_basins)
	selected_by_id = {conformer.id: conformer for conformer in selected}
	assigned_members: dict[int, list[int]] = {}
	members_by_cluster: dict[int, list[int]] = {}
	cluster_ids = [basin.id for basin in selected_basins]
	if len(cluster_ids) != len(set(cluster_ids)):
		raise ValueError("basin IDs must be unique.")

	for basin in selected_basins:
		member_ids: list[int] = []
		for member in basin.members:
			if selected_by_id.get(member.id) is not member:
				assignment_complete = False
				continue
			member_ids.append(member.id)
			assigned_members.setdefault(member.id, []).append(basin.id)
		if len(member_ids) != len(set(member_ids)) or not member_ids:
			assignment_complete = False
		members_by_cluster[basin.id] = member_ids

	if any(len(cluster_assignments) != 1 for cluster_assignments in assigned_members.values()):
		assignment_complete = False
	if set(assigned_members) != set(selected_by_id):
		assignment_complete = False
	cluster_by_conformer = {
		conformer_id: cluster_assignments[0]
		for conformer_id, cluster_assignments in assigned_members.items()
		if len(cluster_assignments) == 1
	}
	for record in conformer_rows:
		record["cluster_id"] = cluster_by_conformer.get(record["conformer_id"])

	valid_populations = [
		row["population"] for row in conformer_rows if row["population_valid"]
	]
	conformer_entropy_result = entropy_statistics(valid_populations)
	cluster_rows: list[dict[str, Any]] = []
	for basin in selected_basins:
		member_id_set = set(members_by_cluster.get(basin.id, []))
		member_records = [
			record for record in conformer_rows
			if record["conformer_id"] in member_id_set
		]
		valid_member_populations = [
			record["population"]
			for record in member_records
			if record["population_valid"]
		]
		cluster_population = (
			math.fsum(valid_member_populations)
			if assignment_complete and valid_member_populations
			else None
		)
		contribution = (
			-cluster_population * math.log(cluster_population)
			if cluster_population is not None and cluster_population > 0.0
			else 0.0 if cluster_population == 0.0 else None
		)
		cluster_rows.append(
			{
				"cluster_id": basin.id,
				"n_conformers": len(basin.members),
				"n_valid_populations": len(valid_member_populations),
				"cluster_population": cluster_population,
				"cluster_entropy_contribution": contribution,
			}
		)

	valid_cluster_populations = [
		row["cluster_population"]
		for row in cluster_rows
		if row["cluster_population"] is not None
	]
	if assignment_complete:
		cluster_entropy_result = entropy_statistics(valid_cluster_populations)
	else:
		cluster_entropy_result = {
			"n_valid_populations": 0,
			"population_sum": None,
			"entropy": None,
			"effective_size": None,
		}
		for row in cluster_rows:
			row["cluster_entropy_contribution"] = None

	population_summary = population_result["summary"]
	return {
		"conformers": conformer_rows,
		"clusters": cluster_rows,
		"summary": {
			"n_conformers": len(selected),
			"n_valid_conformer_populations": len(valid_populations),
			"n_clusters": len(selected_basins),
			"n_valid_cluster_populations": cluster_entropy_result["n_valid_populations"],
			"conformer_entropy": conformer_entropy_result["entropy"],
			"conformer_effective_size": conformer_entropy_result["effective_size"],
			"cluster_entropy": cluster_entropy_result["entropy"],
			"cluster_effective_size": cluster_entropy_result["effective_size"],
			"population_source": "boltzmann",
			"population_sum": population_summary["population_sum"],
			"temperature_K": population_summary["temperature_K"],
			"population_entropy_units": "nats",
			"energy_units": population_summary["energy_units"],
			"clustering_method": clustering_method,
			"clustering_distance": clustering_distance,
			"rmsd_threshold_A": clustering_threshold,
			"cluster_assignment_complete": assignment_complete,
			"cluster_entropy_available": (
				assignment_complete and cluster_entropy_result["entropy"] is not None
			),
			"n_invalid_populations": len(selected) - len(valid_populations),
			"n_unassigned_conformers": len(selected_by_id) - len(cluster_by_conformer),
		},
	}


__all__ = ["analyze_entropy"]